spring.mongodb.uri=mongodb://127.0.0.1
spring.mongodb.database=txn-demo
spring.threads.virtual.enabled=true
logging.level.com.example=warn
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
